### ISSUE TITLE
Multiple skips in a playlist/folder causes ModernX to give up.

### ISSUE THREAD

**Issue by lostb053** [zydezu/ModernX#14]
# Error description:
The interface of ModernX (i think it's called OSC) no longer shows up

# Steps to reproduce:
* Have a folder with multiple medias (preferably without chapters)
* play the folder
* keep jumping to the next video

Additional remarks: I noticed that this doesn't happen when i navigate like this slowly. In the process I noticed that it takes just a little while for OSC to load up completely with size and title n stuff. My assumption is that navigating too quickly results into this situation because script be initially bz sorting out loading for previous file, but i am already on the next one.

# Settings (ModernX)
Note: This .conf file was initially imported from other .conf file while i was using other fork earlier. While i think i've made all necessary changes, feel free to point out any issues here if any.
```
# ---------------- #
# mpv user options #
# ---------------- #

# Duration of fade out in ms
fadeduration=500

# Size ratio of the knob handle
seekbarhandlesize=1


# -------------------- #
# ModernX user options #
# -------------------- #

# Prevent OSC from showing on pause
showonpause=no

# Show title in OSC
showtitle=yes

# =====
# Note: ASS tag's color code is given in BGR, instead of the standard RGB.
# Read the section for "Set color" here:
# https://aeg-dev.github.io/AegiSite/docs/3.2/ass_tags/
# =====

# Accent of the OSC and the title bar
osc_color=000000

# Color of the seekbar progress and handle
seekbarfg_color=E39C42

# Color of the remaining seekbar
seekbarbg_color=FFFFFF

bottomhover=no
showinfo=yes
thumbnailborder=0
showloop=yes
compactmode=no
```

# Screenshot
This screenshot is derived from some logs i think that show up when u press ``` ` ``` in mpv

![image](https://github.com/zydezu/ModernX/assets/72547660/154f8314-9cf0-4f58-b360-aad2e4256fa9)

Feel free to contact for any required info.

**Comment by zydezu** [comment]
I can't recreate this so far. What type of drive are these videos stored on (like a HDD)?

**Comment by lostb053** [comment]
They are on SSD, but ig the power saving mode restricts the speed of OSC? This situation might be very specific for my laptop in that case. Or is it because I'm using bunch of other plugins as well? Does that matter as such? I'm not sure.
Or is it the sheer size of files? As in because the files are it's taking a lil longer. I'm using about 24 files 1.4gb each.

Also note that I'm not really waiting for OSC to load each time i press the PgDwn button (keybinding for Next Video). So like about 3-4 presses/second? See if that helps.

If you are still unable to recreate the issue, is there any way you could still help?

**Comment by lostb053** [comment]
Uh, also i mentioned preferably without chapters, because I've a plug-in which lets me skip chapters instead of videos when i use PgDwn. That also was very specific for me. If you're not using such plug-in, ignore that as well.

**Comment by lostb053** [comment]
Hello. Thx for the reply. Actually i got exams ongoing rn, I'll reply later with time if you don't mind.

**Comment by zydezu** [comment]
This commit https://github.com/zydezu/mpvconfig/commit/309a291c53c97132a13356d98fd876927bb57a5a / the next release addresses a crash related to skipping videos, this could fix the problem

**Comment by lostb053** [comment]
Hey there, I am extremely sorry for failing at giving you the response. I'll be honest, I had forgotten.
Here is my mpv script setup. Some scripts taken from you, some from others.

[mpv.zip](https://github.com/zydezu/ModernX/files/15048414/mpv.zip)

I'll try the update today, and reply you soon.
Thnx for the update, and also thnx for the follow up.

**Comment by lostb053** [comment]
Hey, so i come with more info.

![Screenshot 2024-04-20 160355](https://github.com/zydezu/ModernX/assets/72547660/01df77c6-14e2-45f5-b6aa-91431296dd58)

I say about 5-6 clicks/second

To be noted: It's working much better now. But I still got following error

![Screenshot 2024-04-20 161413](https://github.com/zydezu/ModernX/assets/72547660/6afc0c08-7ef9-4763-8089-004a0d1bc006)

As for me, I think I am satisfied by how it's working now.
maybe just occasional crashes. Feel free to improve if you wish (of course that's well appreciated as well)
Thanks again for the update
