### ISSUE TITLE
Broken subtitles icon

### ISSUE THREAD

**Issue by ThousandDemonDaggers** [zydezu/ModernX#16]
# Error description

ModernX doesn't show correctly "sub = '\239\140\164',"

# Screenshot

![Screenshot from 2024-03-07 11-29-55](https://github.com/zydezu/ModernX/assets/157138369/86832ab3-e975-4bc1-bf1c-4f315cdcb2eb)

**Comment by Xurdejl** [comment]
Have you updated the font files?

**Comment by ThousandDemonDaggers** [comment]
> Have you updated the font files?

I downloaded again the fonts files from 2.7.6 and now everything works correctly, my bad, probably I have used the old ones :)
Anyway, strangely enough 2.7.5 was working correctly.
