### ISSUE TITLE
MOUSE_MOVE input won't work

### ISSUE THREAD

**Issue by inzsome** [zydezu/ModernX#18]
I just switched to ModernX and so far it's really good.
The only thing that's not working right now is my `MOUSE_MOVE` input.

I have a script that should display a OSD message every time I move my mouse. I added this binding to my `input.conf`:

`MOUSE_MOVE script-message my-script`

However, it does not work. I even turned off the keybindings via the `user_opts`. It still doesn't work.
It worked while using osc. Is there any way to fix this?

Edit: Just to test if my script is working properly, I bound the script to a key, instead of `MOUSE_MOVE` and it works.

**Comment by zydezu** [comment]
As of now MOUSE_MOVE is controlled by the modernX script - this overrides commands in input.conf. I'm seeing if this can be changed right now.
