### ISSUE TITLE
OSC Sometimes Crashes and Won't Load

### ISSUE THREAD

**Issue by carycary246** [zydezu/ModernX#19]
Encountered an unusual bug where the OSC will sometimes not load at all after opening a video file. Once the bug happens, the OSC remains broken even if I open the same video back up.

[bug example.webm](https://github.com/zydezu/ModernX/assets/31323333/09b9d86b-dd77-4bfc-86e1-857d345884c9)

This is a test video file that always seems to cause this issue for me on v0.2.2.5 with the following error: modernx.lua:1100: attempt to call global 'normaliseDate' (a nil value). 
https://github.com/zydezu/ModernX/assets/31323333/7c94fbaf-0b36-49cb-93ca-c9cb9d262ed0

On the latest release version the issue doesn't happen consistently but I did see these issues in the console when it does happen.

```2024-03-19 14:43:35,177 [ WARNING] modernx: 
2024-03-19 14:43:35,177 [ WARNING] modernx: stack traceback:
2024-03-19 14:43:35,177 [ WARNING] modernx: ...ale-2x_animejanai-v3/portable_config/scripts/modernx.lua:1139: in function 'handler'
2024-03-19 14:43:35,177 [ WARNING] modernx: mp.defaults:512: in function 'call_event_handlers'
2024-03-19 14:43:35,177 [ WARNING] modernx: mp.defaults:554: in function 'dispatch_events'
2024-03-19 14:43:35,177 [ WARNING] modernx: mp.defaults:505: in function <mp.defaults:504>
2024-03-19 14:43:35,177 [ WARNING] modernx: [C]: at 0x7ff6e8506b50
2024-03-19 14:43:35,177 [ WARNING] modernx: [C]: at 0x7ff6e8505740
2024-03-19 14:43:35,177 [   ERROR] modernx: Lua error: ...ale-2x_animejanai-v3/portable_config/scripts/modernx.lua:1167: attempt to index a nil value```

**Comment by zydezu** [comment]
A version of the video on Github will have different metadata, is it possible for you to send the original file? (my email is kinomaxxing@gmail.com if that helps)

**Comment by zydezu** [comment]
The issues in the console seem to be different from previous versions - could be related to https://github.com/zydezu/ModernX/issues/14

**Comment by carycary246** [comment]
@zydezu I uploaded the test file for you here. Thanks for taking a look at this.
https://mega.nz/file/1GxC2ICI#Z07HQtM86VEGfLA-IXJQrmU6MqqUW70bzWuD_cKNK4s

**Comment by zydezu** [comment]
![2024-03-19_23-16-45_623_mpv](https://github.com/zydezu/ModernX/assets/50119098/84401ee0-4c53-4c13-9bce-3cb1c2195278)
The file seems to work fine on my end, maybe an update to the script will fix the issue...

**Comment by carycary246** [comment]
> The issues in the console seem to be different from previous versions - could be related to #14

So the strange thing is that on the latest version it does not always happen but it may be related that issue. It does seem to happen more frequently when I load a new file, ie episode 1 to episode 2 and the error message is the same as in the first post.

**Comment by zydezu** [comment]
I need to figure out how to recreate it reliably...

**Comment by zydezu** [comment]
https://github.com/zydezu/ModernX/issues/14#issuecomment-2067501878

**Comment by carycary246** [comment]
Tested new version for a bit and have not encountered issue again. Will close as fixed for now.
