### ISSUE TITLE
Volume Control Is Greyed Out When Playing MP3

### ISSUE THREAD

**Issue by blueray453** [zydezu/ModernX#20]
This is a issue mentioned in the main [repo](https://github.com/cyl0/ModernX/issues/53). However, i am using this fork for a long time now.

Here is a screenshot.

![Screenshot](https://user-images.githubusercontent.com/855297/232991493-f45bb740-d01b-4190-be87-c9c2eb4560ed.png)

As you can see I can not change the volume when playing mp3 files. However, up and down arrow or mouse scroll works to increase or decrease volume for mp3 (just can not use the volume control in the OSC).

**Comment by zydezu** [comment]
Please can you send or provide this file.

**Comment by blueray453** [comment]
Do you mean the mp3 file?

**Comment by zydezu** [comment]
Yes

**Comment by blueray453** [comment]
I have added four files. However, you can test with any file.

[Sheikh Sudais.zip](https://github.com/zydezu/ModernX/files/14731006/Sheikh.Sudais.zip)

**Comment by zydezu** [comment]
![2024-03-23_10-11-57_843_mpv](https://github.com/zydezu/ModernX/assets/50119098/26d38b8e-e077-4bd3-9bf0-284bf4777de1)
They seem to work fine for me... perhaps it could be your specific computer setup... do other files work for you?

**Comment by blueray453** [comment]
No mp3 files work for me. This issue is here for about a year now.

**Comment by ThousandDemonDaggers** [comment]
> No mp3 files work for me. This issue is here for about a year now.

Seems you are still using the old fonts files. I had some similar problem, as you can see [here](https://github.com/zydezu/ModernX/issues/16). Maybe installing the new fonts provided with the last release will fix your problem too.

**Comment by blueray453** [comment]
I have removed everything except `modernx_zydezu.lua` and `mpv.conf` and fonts.

the config file has following lines:

```
keep-open=yes
input-ipc-server=/tmp/mpv-socket
screenshot-directory=~/Pictures/
no-window-dragging
reset-on-next-file=pause
osc=no
loop-file=inf
```

For some mp3 there is no GUI. For some mp3 I get the GUI and also the (Volume Control). It is not grayed out. The files I provided you, none of them have any GUI. Are you using any visualizer. Visualizer once sort of solved this problem. please check https://github.com/mpv-player/mpv/issues/6025#issuecomment-1493346580 .

**Comment by blueray453** [comment]
After such a long time `force-window=yes` solved the problem. Thank you very much.
