### ISSUE TITLE
Seekbar chapter title tooltips are slightly out of sync with the actual chapter times

### ISSUE THREAD

**Issue by mo-pi** [zydezu/ModernX#22]
The seekbar markers are in the correct place but the chapter tooltips above the thumbnail are slightly out of sync, to the left on the left side, and to the right on the right side.

https://github.com/zydezu/ModernX/assets/20108256/1432cf1c-0b3c-4c1a-8e22-0d310eddd079

**Comment by mo-pi** [comment]
Should also mention that I edited the lua locally to disable the bottom chapter markers, so only the top ones show in the video.

**Comment by jiangzhenjerry** [comment]
I noticed this issue too. And the degree of out of sync **increases** with number of chapters. So if you have a file with 20+ chapters, towards the end the chapter tooltip is totally messed up.

**Comment by zydezu** [comment]
Does the [latest release](https://github.com/zydezu/ModernX/releases/tag/0.3.4) improve this issue? (Commit: https://github.com/zydezu/ModernX/commit/eb259fb46d7a576faa7d744a65251e9299ff301a)

**Comment by jiangzhenjerry** [comment]
@zydezu The latest release seems to have fixed this issue. Thanks!
