### ISSUE TITLE
How can I assign the 'DEL' key (or any other) to show OSC?

### ISSUE THREAD

**Issue by emk2203** [zydezu/ModernX#25]
For use in a HTPC scenario (no mouse but IR remote), it would be great to have the option to raise the OSC with a button press instead of mouse hovering. 

I had this in the original modernx by @maoiscat by using the following line at the end of the script:

```lua
mp.add_key_binding(nil, 'show_osc', function() show_osc() end)
``` 
and adding `DEL script-binding show_osc` to `input.conf`.

Is this already possible with your fork, or can I just add the same line somewhere in the script at the end where the key bindings are?

**Comment by zydezu** [comment]
This has been fixed in https://github.com/zydezu/ModernX/releases/tag/0.3.1 !! Thank you very much for the issue.
