### ISSUE TITLE
Cannot set 'showwindowtitle' and 'titleBarStrip' to false in script-opts/modernx.conf

### ISSUE THREAD

**Issue by emk2203** [zydezu/ModernX#26]
When I try to set `showwindowtitle` and `titleBarStrip` to 'false' in script-opts/modernx.conf, I get the following errors:

```
   modernx: Error: Can't convert 'false' to boolean!
   modernx: script-opts/modernx.conf:6 error converting value 'false' for key 'showwindowtitle'
   modernx: Error: Can't convert 'false' to boolean!
   modernx: script-opts/modernx.conf:7 error converting value 'false' for key 'titleBarStrip'
```

Any way to fix this? The window title is a bit annoying in fullscreen mode.

This is how the `modernx.conf` file looks:

```
scalefullscreen=2.0
scaleforcedwindow=1.5
hidetimeout=3500
fadeduration=300
minmousemove=2
showwindowtitle=false
titleBarStrip=false
titlefontsize=36
OSCfadealpha=300
timefontsize=24
```

As a workaround, I have changed the values in `scripts/modernx.lua`.

**Comment by zydezu** [comment]
In a conf file, 'false' should be 'no' and 'true' should be 'yes'
