### ISSUE TITLE
The osc doesn't show up when watching youtube videos

### ISSUE THREAD

**Issue by Keith94** [zydezu/ModernX#28]
youtube-dl 2024.5.16
modernx 0.3.5 - worked fine in 0.3.4

**Comment by zydezu** [comment]
Do you mean yt-dlp instead of youtube-dl ?

**Comment by zydezu** [comment]
If possible could you please post a log of errors, (can be shown by pressing ` on the keyboard)

**Comment by novaexe** [comment]
adding to this, it seems like 3.5 broke osc/gui's ability to return from autohide on other websites as well

**Comment by zydezu** [comment]
The script must be 'crashing', please could you press ` and send the screenshot of a log if this happened.

> adding to this, it seems like 3.5 broke osc/gui's ability to return from autohide on other websites as well, useing latest mpvnet/ytdlp/etc

**Comment by novaexe** [comment]
![image](https://github.com/zydezu/ModernX/assets/69226867/6e3cc5e3-0c28-4331-85aa-b0b01d669a73)
![image](https://github.com/zydezu/ModernX/assets/69226867/cd4a0f5b-f318-4369-a8de-c118fdebf219)
![image](https://github.com/zydezu/ModernX/assets/69226867/f934326d-f372-420a-b979-3e31ae444e91)

**Comment by Keith94** [comment]
I installed ytdlp (was using wrong version) and now it's working fine for me.

**Comment by Keith94** [comment]
Nevermind I have the same error posted above

**Comment by zydezu** [comment]
Does the latest version https://github.com/zydezu/ModernX/releases/tag/0.3.5.5 fix this issue?

**Comment by novaexe** [comment]
> Does the latest version https://github.com/zydezu/ModernX/releases/tag/0.3.5.5 fix this issue?

yep, did for me at least tyvm

**Comment by Keith94** [comment]
Works now. Thanks @zydezu !
