### ISSUE TITLE
Color bug with seekbar

### ISSUE THREAD

**Issue by Keith94** [zydezu/ModernX#29]
When you set `seekbarfg_color=` to an orange color like e39c42 (https://www.colorhexa.com/e39c42) the seekbar shows up blue like below

![image](https://github.com/zydezu/ModernX/assets/5490615/e1d5e2c5-2075-468b-bc83-29ce5fad450f)

Same issue happens if you set it to red (ff0000) it shows up dark blue.

EDIT: I think the hex code may need to be written in reverse.. I was confused since this wasn't mentioned anywhere.

**Comment by zydezu** [comment]
Sorry, the format should be in BBGGRR - http://www.tcax.org/docs/ass-specs.htm, a note of this will be in the next version.
![2024-05-26_03-14-08_181_mpv](https://github.com/zydezu/ModernX/assets/50119098/9a384678-f91a-4533-bccb-6a3c66a817ea)
`seekbarfg_color = '429CE3'`
