### ISSUE TITLE
Default variable mismatch

### ISSUE THREAD

**Issue by Flyingtoast** [zydezu/ModernX#31]
Some of the default options for the variables are listed as true/falses, in places where the script only looks for yes/nos. This is the case for at least showinfo and bottomhover, but I wouldn't be surprised if it is technically all of them.

**Comment by zydezu** [comment]
Don't .conf files look for yes/nos whilst editing the .lua file regards true/falses... have I made an error in the readme documentation where I mixed this up?

**Comment by Flyingtoast** [comment]
I don't know, it could be a rookie mistake on my part, because what I did was create a .txt file and renamed it as a .conf file afterwards.
