### ISSUE TITLE
revert seekbar keyframe scrub

### ISSUE THREAD

**Issue by novaexe** [zydezu/ModernX#36]
![image](https://github.com/user-attachments/assets/c00868ee-59bc-4d4c-b124-690effb54b8b)
while i think this is a good feature for ppl that have issues, its very jaring when it doesn't do this for yt-dlp playback / music / thumbfast, so my question is: how do i revert it to 3.5.5?

**Comment by novaexe** [comment]
for context some videos can have the keyframes 10-20 frames behind thumbfasts preview and where u click on the seekbar

**Comment by novaexe** [comment]
in case anyone else runs into this revert this line
![image](https://github.com/user-attachments/assets/2cd244f6-9ce2-4ff1-9572-7f08312e5540)

**Comment by zydezu** [comment]
Fixed in latest version :P ( button mappings are swapped, so Left click is the same as before, whilst shift + left click uses keyframes ) https://github.com/zydezu/ModernX/releases/tag/0.3.6.5
