### ISSUE TITLE
Add playlist button

### ISSUE THREAD

**Issue by bt4ibwem8** [zydezu/ModernX#41]
Could you please add button (to the bottom right place) which show playlist? I know there is F8 for doing it but would be nice to have option to enable/disable it, same as you made it with other buttons...

**Comment by zydezu** [comment]
Technically Shift+Clicking the Next Video button does this.

**Comment by bt4ibwem8** [comment]
Yes, you are right. Could modernx script make the items in the playlist clickable? So i could choose the item with mouse click...
