### ISSUE TITLE
Add pause indicator

### ISSUE THREAD

**Issue by Keith94** [zydezu/ModernX#46]
https://hunden.linuxkompis.se/2018/09/13/adding-a-pause-indicator-to-mpv-media-player.html

Would be nice to have pause indicator built in with these changes made too.

Also not sure if the above script can be achieved with simpler code, since it was originally designed to be a progress bar script.

**Comment by Samillion** [comment]
```lua
local pause_ind = mp.create_osd_overlay('ass-events')
pause_ind.data = [[{\an5\p1\alpha&H79\1c&Hffffff&\3a&Hff\pos(760,440)}]] .. [[m-145 -75 l -105 -75 l -105 75 l -145 75 m-55 -75 l -15 -75 l -15 75 l -55 75]]

mp.observe_property('pause', 'bool', function(_, paused)
	mp.add_timeout(0.1, function()
		if paused then pause_ind:update()
		else pause_ind:remove() end
	end)
end)
```

![image](https://github.com/user-attachments/assets/a3e10f00-3585-4f3c-948e-a01d25363033)
