### ISSUE TITLE
Loading description

### ISSUE THREAD

**Issue by bt4ibwem8** [zydezu/ModernX#55]
Description works for youtube videos and local movies/shows, but it is stucked for iptv streaming content. You could implement some useful info for TV live streaming, for example codecs, refresh rate, resolution (ideally configurable):
- h265/AAC
- h265/AAC 50Hz 1080p
- 1920 x 1080
- Bitrate: 2.5 Mbps

![image](https://github.com/user-attachments/assets/29aa82f6-341a-43bf-8701-f4f798915658)

**Comment by zydezu** [comment]
How could I replicate this issue?

**Comment by bt4ibwem8** [comment]
Enable description in your script and then run any hls stream from any .m3u or .m3u8 playlist you find on the internet.

**Comment by zydezu** [comment]
Fixed for next release.
