### ISSUE TITLE
Streaming video breaks the OSC

### ISSUE THREAD

**Issue by NatsuDzn** [zydezu/ModernX#6]
Opening any video url (except youtube videos/links) breaks the OSC

```
[modernx]
[modernx] stack traceback:
[modernx]       mp.defaults:640: in function 'handler'
[modernx]       mp.defaults:512: in function 'call_event_handlers'
[modernx]       mp.defaults:554: in function 'dispatch_events'
[modernx]       mp.defaults:505: in function <mp.defaults:504>
[modernx]       [C]: at 0x7ff7536675a0
[modernx]       [C]: at 0x7ff753666190
[modernx] Lua error: C:\Users\user\AppData\Roaming/mpv/scripts/modernx.lua:1466: attempt to concatenate field 'youtubeuploader' (a nil value)
```

mpv version: mpv v0.37.0-198-ga39f9b61

Example: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

To reproduce: `mpv http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4`

**Comment by zydezu** [comment]
fixed in https://github.com/zydezu/mpvconfig/commit/264d9d068bbcdd481290c6ea7db2db6e8a89c356, release following shortly..

**Comment by zydezu** [comment]
Released as https://github.com/zydezu/ModernX/releases/tag/0.2.6.5
