### ISSUE TITLE
Any way i can remove this dot in the progress bar?

### ISSUE THREAD

**Issue by HornyPrivateGamer** [zydezu/ModernX#62]
![image](https://github.com/user-attachments/assets/f9e95049-1a46-476f-9d60-7965a00e3137)

Like what i said in the description. 
that on big TV this dot can be wayyy to big 

@zydezu  Please thanks very much begging you

**Comment by HornyPrivateGamer** [comment]
[modernx.zip](https://github.com/user-attachments/files/17686455/modernx.zip)
This is my version of Modern X 
It is not a virus, if you open the zip it is jsut a .Lua file

**Comment by HornyPrivateGamer** [comment]
Just change 
ass_draw_cir_cw(ass, xp, elem_geo.h / 2, rh)
To
-- ass_draw_cir_cw(ass, xp, elem_geo.h / 2, rh)

**Comment by zydezu** [comment]
user_opts.seekbarhandlesize

**Comment by HornyPrivateGamer** [comment]
> user_opts.seekbarhandlesize

thans a lot man, also my way works too. i used ChatGPT help me out a bit
```

ass_draw_cir_cw(ass, xp, elem_geo.h / 2, rh)
To
-- ass_draw_cir_cw(ass, xp, elem_geo.h / 2, rh)


```
