### ISSUE TITLE
How to hide size for local files

### ISSUE THREAD

**Issue by Keith94** [zydezu/ModernX#7]
![image](https://github.com/zydezu/ModernX/assets/5490615/287cff11-4447-48a5-bdc1-4e23f7778745)

**Comment by Keith94** [comment]
The issue is present in v0.2.4 but doesn't happen in v2.0.3.5

**Comment by Keith94** [comment]
I had to modify `state.localDescription = "Size: " .. file_size` to `state.localDescription = ""` but there should be an option to turn it off maybe?

**Comment by zydezu** [comment]
Fixed in https://github.com/zydezu/mpvconfig/commit/326b096efb884dd190fb316dc8a0e13311f335ee, release coming soon...

**Comment by Keith94** [comment]
Thanks!
