### ISSUE TITLE
The chapter list doesn't appear in OSC when navigating chapters

### ISSUE THREAD

**Issue by Keith94** [zydezu/ModernX#9]
The following text doesn't appear like in the stock OSC

![image](https://github.com/zydezu/ModernX/assets/5490615/37faccfb-81ce-4bcd-8356-baf8b54b741e)

**Comment by zydezu** [comment]
I don't understand this issue- please can you elaborate?

**Comment by Keith94** [comment]
Never mind, I think it's intended behavior. The chapter list only appears when right clicking the skip forward/back buttons, unlike the default OSC it appears when left clicking.
